-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.angsurans
(
    id_pembayaran serial NOT NULL,
    id_pinjaman integer NOT NULL,
    jumlah_angsuran numeric(15, 2) NOT NULL,
    tanggal_pembayaran timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    keterangan text COLLATE pg_catalog."default",
    CONSTRAINT angsurans_pkey PRIMARY KEY (id_pembayaran)
);

CREATE TABLE IF NOT EXISTS public.karyawan
(
    id_karyawan serial NOT NULL,
    nama_karyawan character varying(100) COLLATE pg_catalog."default" NOT NULL,
    jabatan character varying(50) COLLATE pg_catalog."default" NOT NULL,
    tanggal_lahir date NOT NULL,
    alamat text COLLATE pg_catalog."default" NOT NULL,
    jenis_kelamin character varying(10) COLLATE pg_catalog."default" NOT NULL,
    kontak character varying(20) COLLATE pg_catalog."default" NOT NULL,
    karyawan_sejak timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    available boolean NOT NULL DEFAULT true,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT karyawan_pkey PRIMARY KEY (id_karyawan),
    CONSTRAINT karyawan_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.nasabahs
(
    id_nasabah serial NOT NULL,
    nik character varying(16) COLLATE pg_catalog."default" NOT NULL,
    nama character varying(100) COLLATE pg_catalog."default" NOT NULL,
    ttl date NOT NULL,
    alamat text COLLATE pg_catalog."default" NOT NULL,
    rt_rw character varying(20) COLLATE pg_catalog."default",
    kelurahan character varying(50) COLLATE pg_catalog."default",
    pekerjaan character varying(50) COLLATE pg_catalog."default",
    agama character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT nasabahs_pkey PRIMARY KEY (id_nasabah),
    CONSTRAINT nasabahs_nik_key UNIQUE (nik)
);

CREATE TABLE IF NOT EXISTS public.pengeluarans
(
    id_pengeluaran serial NOT NULL,
    nama_pengeluaran character varying(200) COLLATE pg_catalog."default" NOT NULL,
    tanggal_pengeluaran timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_pengeluaran numeric(15, 2) NOT NULL,
    keterangan text COLLATE pg_catalog."default",
    CONSTRAINT pengeluarans_pkey PRIMARY KEY (id_pengeluaran)
);

CREATE TABLE IF NOT EXISTS public.pinjamans
(
    id_pinjaman serial NOT NULL,
    id_nasabah integer NOT NULL,
    jumlah_pinjaman numeric(15, 2) NOT NULL,
    keterangan text COLLATE pg_catalog."default",
    durasi integer NOT NULL,
    bunga numeric(5, 2) NOT NULL,
    saldo_pinjaman numeric(15, 2) NOT NULL,
    createdat timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pinjamans_pkey PRIMARY KEY (id_pinjaman)
);

ALTER TABLE IF EXISTS public.angsurans
    ADD CONSTRAINT angsurans_id_pinjaman_fkey FOREIGN KEY (id_pinjaman)
    REFERENCES public.pinjamans (id_pinjaman) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.pinjamans
    ADD CONSTRAINT pinjamans_id_nasabah_fkey FOREIGN KEY (id_nasabah)
    REFERENCES public.nasabahs (id_nasabah) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;